"""Localized explanations for controls and workspaces (no network/model work)."""
EXTRA = {
    "tip_stage_audio": ("Применяет настройки вкладки «Звук» к выходным копиям. Не применяет правки из редактора.", "Applies Sound tab settings to output copies. Does not include editor changes."),
    "tip_stage_metadata": ("Обновляет теги выходных копий значениями вкладки «Метаданные».", "Updates output tags using the Metadata tab fields."),
    "tip_stage_lyrics": ("Читает существующий текст или распознаёт новый в отдельном этапе. Надёжные строки сохраняет с таймкодами в MP3 USLT.", "Reads existing lyrics or recognizes new lyrics in a separate stage. Reliable timed lines are stored in MP3 USLT."),
    "tip_stage_cover": ("Генерирует обложку с выбранными настройками. При включённом встраивании записывает её в выходную песню.", "Generates artwork with selected settings. Embeds into output audio when embedding is enabled."),
    "tip_language_button": ("Переключает язык интерфейса, не язык распознавания песен.", "Switches the interface language, not the lyric recognition language."),
    "tip_help": ("Объяснения по открытой вкладке и её параметрам. F1 открывает ту же справку.", "Help for the open tab and its controls. F1 opens the same help."),
    "tab_editor": ("Редактор", "Editor"),
    "help": ("? Справка", "? Help"),
    "help_hint": ("Правый щелчок — подсказка • F1 — справка по вкладке", "Right-click for tips • F1 — help for this tab"),
    "audio_changes": ("Что именно изменится", "Exactly what changes"),
    "audio_scope": ("Настройки ниже используются только для сравнения и этапа «Звук» в «Выполнении». Редактор работает отдельно.", "These settings apply to comparison and the Sound stage in Processing only. The editor is independent."),
    "audio_intensity_value": ("Сила профиля: {value:.0f}%", "Profile strength: {value:.0f}%"),
    "audio_summary": ("Громкость → {lufs:.1f} LUFS • Бас {bass:+.2f} dB • Высокие {treble:+.2f} dB • Стерео ×{width:.2f}\nПики ≤ {peak:.1f} dBTP • Средние {mid:+.2f} dB • Усиление ×{gain:.2f}", "Loudness → {lufs:.1f} LUFS • Bass {bass:+.2f} dB • Treble {treble:+.2f} dB • Stereo ×{width:.2f}\nPeaks ≤ {peak:.1f} dBTP • Mids {mid:+.2f} dB • Gain ×{gain:.2f}"),
    "tip_audio_loudness": ("Меняет целевую среднюю громкость, не просто громкость воспроизведения. Число LUFS в блоке ниже показывает итоговую настройку. Чем ближе к нулю, тем громче.", "Changes target average loudness, not player volume. The LUFS value below shows the actual target; closer to zero is louder."),
    "tip_audio_character": ("Мягче ослабляет высокие частоты, ярче усиливает их. Фактическое усиление показано в dB ниже. Средние частоты меняются только в дополнительных настройках.", "Softer cuts treble; brighter boosts it. Actual gain in dB is shown below. Mids are adjusted in advanced settings only."),
    "tip_audio_bass_macro": ("Усиливает или ослабляет низкие частоты. 0 dB сохраняет исходный бас. Интенсивность уменьшает или усиливает действие ползунка.", "Boosts or cuts low frequencies. 0 dB preserves source bass. Intensity scales this slider's effect."),
    "tip_audio_space": ("Изменяет ширину стерео. ×1.00 сохраняет исходную ширину, меньше — уже, больше — шире. Монофайл не получает настоящего стерео.", "Adjusts stereo width. ×1.00 keeps source width; lower narrows, higher widens. Mono cannot gain real stereo detail."),
    "tip_audio_auto_denoise": ("Проверяет постоянный фоновый шум и включает фильтр только при его обнаружении. Это не удаление вокала и не восстановление повреждённой записи.", "Checks for stationary noise and applies a filter only if detected. Not vocal removal or restoration of damaged audio."),
    "tip_audio_peak_protection": ("Лимитер сдерживает пики после обработки. Уменьшает риск перегруза, но не устраняет искажения, уже записанные в оригинале.", "Limits peaks after processing to reduce clipping. Cannot fix distortion already recorded in the original."),
    "tip_audio_analyze": ("Измеряет громкость, динамику, частотный баланс и шум выбранного файла в фоне. Ничего не записывает. Рекомендация применяется отдельной кнопкой.", "Measures loudness, dynamics, frequency balance and noise in the background. No file writes; apply the recommendation separately."),
    "tip_audio_apply_recommendation": ("Выбирает профиль по результатам анализа и меняет настройки. Для проверки нажмите «Создать сравнение».", "Selects a profile from analysis and changes settings. Use Create comparison to hear the result."),
    "tip_audio_preview": ("Создаёт две временные версии для сравнения при одинаковой воспринимаемой громкости. Не изменяет оригинал и не запускает «Выполнение».", "Creates temporary original/processed versions matched in perceived loudness. Does not alter the source or start Processing."),
    "tip_audio_original": ("Воспроизводит исходный звук из подготовленного сравнения.", "Plays the source version from the prepared comparison."),
    "tip_audio_processed": ("Воспроизводит звук после текущих настроек. После изменения настроек создайте сравнение заново.", "Plays the processed comparison. Recreate comparison after changing settings."),
    "tip_audio_stop": ("Останавливает прослушивание сравнения.", "Stops comparison playback."),
    "tip_advanced_audio": ("Точные значения эквалайзера, громкости, фильтров, компрессора и эффектов. Правки не сбрасываются при создании сравнения.", "Precise EQ, loudness, filters, compressor and effects. Values are retained when comparison is created."),
    "tip_artist": ("Исполнитель песни. Пустое поле сохраняет существующий тег при обычном обновлении.", "Song artist. An empty field preserves the tag in normal update mode."),
    "tip_album": ("Название альбома, записываемое в метаданные выходного файла.", "Album name stored in output metadata."),
    "tip_album_artist": ("Общий исполнитель альбома; для сборника может отличаться от исполнителя песни.", "Overall album artist, which can differ from the song artist on compilations."),
    "tip_composer": ("Автор музыки. Не исполнитель и не автор текста.", "Music composer, not necessarily the performer or lyricist."),
    "tip_date": ("Год или дата выпуска, например 2026.", "Release year or date, for example 2026."),
    "tip_track": ("Порядковый номер песни в альбоме, например 3 или 3/12.", "Track number in the album, such as 3 or 3/12."),
    "tip_comment": ("Комментарий в метаданных, не описание для генерации обложки. Описание обложки выводится из текста автоматически.", "Metadata comment, not a cover prompt. The cover description comes from lyrics automatically."),
    "tip_disc": ("Номер диска в издании, например 1/2.", "Disc number in the release, such as 1/2."),
    "tip_publisher": ("Издатель или лейбл в метаданных.", "Publisher or record label stored in metadata."),
    "tip_copyright": ("Сведения об авторских правах в метаданных.", "Copyright information stored in metadata."),
    "tip_lyrics": ("Дополнительный текстовый тег метаданных. Для распознавания и синхронизированных строк используйте вкладку «Текст песни».", "Additional plain lyric metadata. Use the Lyrics tab for recognition and timed lines."),
    "tip_choose_file": ("Выбирает один исходный файл для обработки, анализа, обложки или текста. Не добавляет его в редактор.", "Selects one processing source for analysis, cover or lyrics. Does not add it to the editor."),
    "tip_choose_folder": ("Выбирает папку для пакетной обработки. Результат — соседняя SonicForgeProgect, не внутри источника.", "Selects a folder for batch processing. Output is a sibling SonicForgeProgect, not inside the source."),
    "tip_choose": ("Меняет папку для готовых копий пакетной обработки. Редактор выбирает выходной файл отдельно.", "Changes the batch output folder. The editor selects its export file separately."),
    "tip_metadata_actions": ("Прочитать теги исходного файла, открыть дополнительные поля или создать копию без метаданных.", "Read source tags, open additional fields or produce a copy without metadata."),
    "tip_additional_metadata": ("Номер диска, издатель, авторские права и дополнительный текстовый тег.", "Disc number, publisher, copyright and an additional text tag."),
    "tip_cover_show_title": ("Печатает название по центру обложки. Название берётся из метаданных или имени файла.", "Prints the title in the center, from metadata or the filename."),
    "tip_cover_show_artist": ("Добавляет исполнителя к надписи на обложке, если включено название.", "Adds the artist to the cover lettering when title is enabled."),
    "tip_embed_cover_short": ("В «Выполнении» записывает готовую картинку в аудиофайл. Предпросмотр показывает картинку, но не меняет песню.", "Processing embeds the completed image in audio. Preview displays an image without changing the song."),
    "tip_cover_preview": ("Создаёт и показывает обложку в этом окне. Не запускает выполнение и не встраивает её в исходную песню.", "Generates and displays artwork here. Does not start Processing or embed into the source."),
    "tip_overwrite_lyrics": ("При пакетном распознавании разрешает заменить уже существующий текст. Если выключено, существующий текст сохраняется.", "Allows batch recognition to replace existing lyrics. When off, existing lyrics are preserved."),
    "tip_highpass_hz": ("Частоты ниже этого порога срезаются только при включённом фильтре низких частот. Единица — Hz.", "Frequencies below this cutoff are removed only with the high-pass filter enabled. Unit: Hz."),
    "tip_lowpass_hz": ("Частоты выше этого порога срезаются только при включённом фильтре высоких частот. Единица — Hz.", "Frequencies above this cutoff are removed only with the low-pass filter enabled. Unit: Hz."),
    "tip_copy_log": ("Копирует весь журнал выполнения в буфер обмена.", "Copies the entire processing log to the clipboard."),
    "tip_clear_log": ("Очищает только видимый журнал, не файлы и не настройки.", "Clears the visible log only, not files or settings."),
}

PAGES = {
    "settings": ("1. Выберите русский или английский язык интерфейса. Названия разделов и параметров изменятся сразу, без перезапуска.\n2. Язык распознавания песен выбирается отдельно в разделе «Текст песни».\n3. Параметр экрана загрузки определяет, показывать ли заставку при следующих запусках приложения.", "1. Choose Russian or English for the interface. Section and control labels change immediately without restarting.\n2. Set lyric recognition language separately in Lyrics.\n3. The loading screen preference controls the splash on future launches."),
    "editor": (
        "1. Добавьте аудио кнопкой или перетащите файл из Проводника. Бросок ниже последней дорожки создаёт новую; число дорожек не ограничено.\n"
        "2. Щелчок выбирает фрагмент и курсор. Обычное перетаскивание переносит весь фрагмент, в том числе между дорожками. На одной дорожке фрагменты не наслаиваются.\n"
        "3. Shift + перетаскивание выделяет участок. Поля «От» / «До» задают время от начала фрагмента с шагом 1 мс; «Выделить» подтверждает его. «Начать выделение» отмечает красный курсор, «Завершить выделение» — конец; работает и при прослушивании. Esc отменяет незавершённый выбор. «К выделению» приближает участок. «Удалить выделение» соединяет оставшиеся части без паузы, со сглаживанием до 40 мс. Отмена возвращает исходный звук. «Разделить» режет у курсора.\n"
        "4. «Вокал и инструменты» заменяет выбранный фрагмент на 2 или 4 составляющие на отдельных дорожках. Процесс локальный, может занять минуты; возможны примеси и артефакты. Отмена возвращает исходный фрагмент.\n"
        "5. Прослушайте результат и экспортируйте в новый WAV, MP3 или M4A. Черновик сохраняет пути и правки. Редактор независим от «Выполнения»; исходники не меняются.",
        "1. Add audio with the button or drop files from Explorer. Drop below the last lane to create another; there is no fixed lane limit.\n"
        "2. Click to select a clip and cursor. Normal dragging moves the entire clip, including between lanes. Clips on one lane do not overlap.\n"
        "3. Shift-drag a range, or enter clip-relative From / To times with a 1 ms step and click Select. Start selection marks the red cursor, Finish selection marks the end; works during playback. Esc cancels the unfinished choice. Zoom selection magnifies the range. Remove selection joins the remaining parts without a gap, using a crossfade of up to 40 ms. Undo restores the original. Split cuts at the cursor; normal dragging never cuts audio.\n"
        "4. Vocals and instruments replaces the selected clip with 2 or 4 components on separate lanes. Local processing may take minutes and leave audio bleed. Undo restores the original clip.\n"
        "5. Listen and export a new WAV, MP3 or M4A. Drafts save paths and edits. The editor is independent of Processing; originals remain intact."),
    "metadata": ("Поля записываются в готовые копии при этапе «Метаданные». «Прочитать» заполняет их из выбранного файла. При обычном обновлении пустые поля сохраняют существующие значения; перезапись всех метаданных удаляет прежние теги. Комментарий — тег, а не ручное описание обложки.", "Fields are written to completed copies in the Metadata stage. Read fills them from the selected file. Normal updates retain existing values for empty fields; replacing all metadata removes old tags. Comment is a tag, not a manual cover prompt."),
    "audio": ("1. Выберите желаемый результат и интенсивность. Ползунки меняют громкость, высокие частоты, бас и ширину стерео. Блок «Что именно изменится» показывает реальные значения.\n2. «Анализировать» измеряет запись; рекомендация применяется отдельно.\n3. «Создать сравнение» подготавливает оригинал и результат с одинаковой воспринимаемой громкостью.\n4. Готовые копии создаёт только этап «Звук» во вкладке «Выполнение». Эти настройки не влияют на редактор.\n\n0% не означает обход всей обработки: остаётся нормализация; дополнительные эффекты и фильтры управляются отдельно.", "1. Choose a profile and strength. Sliders adjust loudness, treble, bass and stereo width. Exactly what changes shows actual values.\n2. Analyze measures the recording; apply recommendations separately.\n3. Create comparison prepares loudness-matched original and processed versions.\n4. Final copies are made by the Sound stage in Processing only. These settings do not affect the editor.\n\n0% is not full bypass: normalization remains; advanced effects and filters are independent."),
    "cover": ("Создайте обложку автоматически или выберите свой PNG, JPEG либо WebP. Предпросмотр показывает готовую картинку здесь, не меняя исходный файл. Для генерации текст песни влияет на цвета и настроение, а название и исполнитель управляют центральной надписью. Встраивание происходит при выполнении этапа обложки.", "Generate artwork automatically or choose your own PNG, JPEG or WebP. Preview shows it here without modifying the source. For generated artwork, lyrics influence mood and colors while title and artist control the lettering. Embedding happens during the Cover stage."),
    "lyrics": ("«Открыть готовый» читает текст из песни или соседнего TXT/LRC. «Распознать» выводит услышанные строки. Русский и английский сохраняются как есть; для остальных языков по умолчанию используется русская транскрипция звуков, не перевод. MP3 сохраняет строки с таймкодами в USLT; пользователь видит слова без таймкодов. «Записать в песню» записывает текущий текст в выбранный MP3. Ненадёжный результат требует проверки.", "Load existing reads song tags or a nearby TXT/LRC. Recognize displays detected lines. Russian and English stay native; other languages default to Russian sound spelling, not translation. MP3 stores timed lines in USLT while the editor shows words without timestamps. Save writes current text to the selected MP3. Uncertain results need review."),
    "processing": ("Выберите этапы и источник. Для папки обрабатываются её песни; результат сохраняется в соседнюю SonicForgeProgect. Оригиналы сохраняются. Отдельный индикатор текста показывает распознавание, запись и сомнительные результаты. Редактор сюда не входит: он экспортирует отдельно. «Стоп» прерывает выполнение; готовые результаты и незавершённые файлы обрабатываются согласно журналу.", "Choose stages and a source. Folder processing writes into a sibling SonicForgeProgect. Originals are preserved. Separate lyric progress reports recognition, saving and review. The editor is not a stage and exports separately. Stop cancels processing; see the log for completed/incomplete outputs."),
}


def add_help_strings(translations):
    for key, values in EXTRA.items():
        for index, language in enumerate(("ru", "en")):
            translations[language][key] = values[index]
